### PR TITLE
Context becomes parameters

### PR DESCRIPTION
**Pull request by cgrigis**
WiP, to be discussed whether I am in the right direction. :)

Fixes c4dt/lattigo#1

### CODE REVIEW

**Comment by ChristianMct** [comment]
This is the direction we want to take for these pre-computed values. Is there a specific reason why you think `EncoderContext` should be a public type and have a public constructor ? We didn't plan on exposing these, initially.

**Comment by cgrigis** [comment]
> Is there a specific reason why you think `EncoderContext` should be a public type and have a public constructor ? We didn't plan on exposing these, initially.

Good point, no specific reason, making it private now.

**Comment by cgrigis** [comment]
So, my understanding is that the same approach goes for `NewKeyGenerator()`, `newEncryptor()`, `NewDecryptor()`, `NewEvaluator()`, `NewPlaintext()` and `NewCiphertext()`, correct?

**Comment by ChristianMct** [comment]
That's correct. Moreover, most of these contexts structs will have
common attributes. So this could be done elegantly using struct embedding.

**Comment by ChristianMct** [comment]
Close this PR as now duplicated.

**Pull request closed without merging**
